### ISSUE TITLE
Better Seqta Support

### ISSUE THREAD

**Issue by SirLuca100** [fnleaksandinfo/SEQTAVanced#2]
Can you please add better seqta support, I can't use both extensions at the same time so I can only use one.

**Comment by maxtull** [comment]
Heyo, there are currently no plans to fully support BetterSEQTA due to way both extensions function - there would be a clash between various things that would require changes from both myself and BetterSEQTA. However, I do plan on supporting a few aspects of BetterSEQTA in the future, such as the additional menu items and other UI elements. Cheers.
